// =============================================
// EXPORT MODULE — PDF, Text, JSON export
// =============================================

const Exporter = (() => {

    // ── Plain text download ──────────────────────
    const downloadText = (content, filename = 'feedback.txt') => {
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    // ── JSON export ──────────────────────────────
    const downloadJSON = (data, filename = 'insights.json') => {
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    // ── Build full text report ───────────────────
    const buildTextReport = (assignment, feedback, insights) => {
        const separator = '─'.repeat(60);
        const lines = [];

        lines.push('═'.repeat(60));
        lines.push(`  AI ASSIGNMENT ANALYTICS REPORT`);
        lines.push(`  PS ID: PS5D146E`);
        lines.push('═'.repeat(60));
        lines.push(`Assignment : ${assignment.title}`);
        lines.push(`Subject    : ${assignment.subject}`);
        lines.push(`Generated  : ${new Date().toLocaleString()}`);
        lines.push('');
        lines.push(separator);
        lines.push('CLASS SUMMARY');
        lines.push(separator);
        lines.push(feedback.summary);
        lines.push('');

        lines.push(separator);
        lines.push('QUESTION-WISE FEEDBACK');
        lines.push(separator);
        feedback.questionDrafts.forEach((qd, i) => {
            lines.push(`\n[Q${i + 1}] ${qd.question}`);
            lines.push(`Status: ${qd.status.toUpperCase()}`);
            lines.push(qd.draft);
        });

        if (feedback.studentDrafts?.length > 0) {
            lines.push('');
            lines.push(separator);
            lines.push('STUDENT-LEVEL FEEDBACK DRAFTS');
            lines.push(separator);
            feedback.studentDrafts.forEach(sd => {
                lines.push(`\n${sd.draft}`);
                lines.push(`Status: ${sd.status.toUpperCase()}`);
            });
        }

        lines.push('');
        lines.push(separator);
        lines.push('AI CONFIDENCE NOTES');
        lines.push(separator);
        insights.commonMistakes?.forEach(cm => {
            cm.mistakes?.forEach(m => {
                lines.push(`• Pattern "${m.phrase}" — Confidence: ${m.confidence}%, Occurrences: ${m.count}`);
            });
        });

        lines.push('');
        lines.push('─'.repeat(60));
        lines.push('Generated by EduInsight AI | Hackathon Edition | PS5D146E');
        return lines.join('\n');
    };

    // ── PDF via print window ─────────────────────
    const printReport = (assignment, feedback, insights) => {
        const htmlContent = buildPrintHTML(assignment, feedback, insights);
        const win = window.open('', '_blank');
        win.document.write(htmlContent);
        win.document.close();
        win.focus();
        setTimeout(() => win.print(), 600);
    };

    const buildPrintHTML = (assignment, feedback, insights) => {
        const qRows = feedback.questionDrafts.map((qd, i) => `
      <div class="section">
        <h3>Q${i + 1}: ${escHtml(qd.question)}</h3>
        <span class="badge badge-${qd.status}">${qd.status}</span>
        <pre>${escHtml(qd.draft)}</pre>
      </div>`).join('');

        const mistakeRows = (insights.commonMistakes || []).map(cm =>
            cm.mistakes.map(m => `
        <tr>
          <td>${escHtml(cm.question)}</td>
          <td><code>${escHtml(m.phrase)}</code></td>
          <td>${m.count}</td>
          <td>${m.confidence}%</td>
          <td>${m.examples.map(e => `<em>"${escHtml(e)}"</em>`).join('<br>')}</td>
        </tr>`).join('')
        ).join('');

        return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>EduInsight AI Report — ${escHtml(assignment.title)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #111; background: #fff; padding: 32px; }
  h1 { font-size: 22px; color: #1a1a2e; border-bottom: 3px solid #7c3aed; padding-bottom: 8px; margin-bottom: 16px; }
  h2 { font-size: 17px; color: #5b21b6; margin: 24px 0 10px; }
  h3 { font-size: 14px; color: #374151; margin-bottom: 6px; }
  .meta { font-size: 12px; color: #6b7280; margin-bottom: 24px; }
  .meta span { margin-right: 20px; }
  .section { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 14px; page-break-inside: avoid; }
  pre { white-space: pre-wrap; font-size: 13px; color: #374151; margin-top: 8px; background: #f9fafb; padding: 12px; border-radius: 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 10px; }
  th { background: #7c3aed; color: #fff; padding: 8px; text-align: left; }
  td { padding: 7px 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
  tr:nth-child(even) td { background: #f5f3ff; }
  code { background: #ede9fe; padding: 2px 6px; border-radius: 4px; font-size: 11px; }
  em { color: #6b7280; font-style: italic; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; text-transform: uppercase; margin-bottom: 8px; }
  .badge-approved { background: #d1fae5; color: #065f46; }
  .badge-rejected { background: #fee2e2; color: #991b1b; }
  .badge-pending  { background: #fef3c7; color: #92400e; }
  .stats-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; margin: 16px 0; }
  .stat-box { border: 1px solid #ddd; border-radius: 8px; padding: 12px; text-align: center; }
  .stat-box .num { font-size: 28px; font-weight: 700; color: #7c3aed; }
  .stat-box .lbl { font-size: 11px; color: #6b7280; margin-top: 4px; }
  footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 12px; }
  @media print { body { padding: 16px; } }
</style>
</head>
<body>
<h1>📊 EduInsight AI — Assignment Analytics Report</h1>
<div class="meta">
  <span><strong>Assignment:</strong> ${escHtml(assignment.title)}</span>
  <span><strong>Subject:</strong> ${escHtml(assignment.subject)}</span>
  <span><strong>PS ID:</strong> PS5D146E</span>
  <span><strong>Generated:</strong> ${new Date().toLocaleString()}</span>
</div>

<div class="stats-grid">
  <div class="stat-box"><div class="num">${insights.classAvg}%</div><div class="lbl">Class Average</div></div>
  <div class="stat-box"><div class="num">${insights.totalStudents}</div><div class="lbl">Students</div></div>
  <div class="stat-box"><div class="num">${insights.perfBands.high.length}</div><div class="lbl">High Performers</div></div>
  <div class="stat-box"><div class="num">${insights.perfBands.struggling.length}</div><div class="lbl">Need Support</div></div>
</div>

<h2>📝 Class Summary</h2>
<div class="section"><pre>${escHtml(feedback.summary)}</pre></div>

<h2>📋 Question-wise Feedback</h2>
${qRows}

<h2>🔍 Common Mistakes (AI Detected)</h2>
<table>
  <thead><tr><th>Question</th><th>Pattern</th><th>Count</th><th>Confidence</th><th>Example Response</th></tr></thead>
  <tbody>${mistakeRows || '<tr><td colspan="5">No significant patterns detected</td></tr>'}</tbody>
</table>

<footer>Generated by EduInsight AI &nbsp;|&nbsp; Hackathon Edition &nbsp;|&nbsp; PS ID: PS5D146E</footer>
</body></html>`;
    };

    const escHtml = str => String(str)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

    return { downloadText, downloadJSON, buildTextReport, printReport };
})();
